# https://taskfile.dev

version: "3"

dotenv:
  - .env

includes:
  build: ./scripts/BuildTasks.yml
  db: ./scripts/DbTasks.yml
  deps: ./scripts/DepsTasks.yml
  app: ./scripts/RunTasks.yml
  test: ./scripts/TestsTasks.yml
  view: ./scripts/ViewsTasks.yml

tasks:
  default:
    silent: true
    cmds:
      - task: help

  help:
    desc: Show this help.
    silent: true
    aliases:
      - h
    cmds:
      - task --list

  clean:
    desc: Clean the task cache and remove the .task directory.
    silent: true
    cmds:
      - echo "Cleaning the task cache and removing the .task directory..."
      - rm -rf .task
      - rm -rf ./bin
      - rm -rf ./tmp
      - go clean -cache
      - echo "Task cache cleaned."

  errtrace:
    desc: Instrument the code with error trace wrapper.
    silent: true
    aliases: ["err"]
    cmds:
      - echo "Adding errtrace to generated files..."
      - errtrace -w ./...

  dev:
    desc: Run the application in development mode.
    silent: false
    preconditions:
      - test -f .env
      - test -f ./scripts/.air.toml
      - test -f ./db/local.db
    deps:
      - task: db:redis
      - task: db:sqlc
      - task: view
      - task: errtrace
    cmds:
      - task: db:migrate
      - air -c ./scripts/.air.toml
