// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"
import "braces.dev/errtrace"

type InputType string

// String returns the string representation of the InputType
func (i InputType) String() string {
	return string(i)
}

const (
	Text     InputType = "text"
	Email    InputType = "email"
	Password InputType = "password"
	Hidden   InputType = "hidden"
)

type Input struct {
	Type         InputType
	ID           string
	Name         string
	Label        string
	Placeholder  string
	Autocomplete string
	Required     bool
	ActionURL    string
	ActionLabel  string
	Value        string
	Errors       []string
}

// GetInputID returns the ID of the input
func (c Input) GetInputID() string {
	if c.ID != "" {
		return c.ID
	}
	return c.Name
}

// GetInputType returns the type of the input
func (c Input) GetInputType() string {
	if c.Type == "" {
		return Text.String()
	}
	return c.Type.String()
}

// GetActionURL returns the action URL of the input
func (c Input) GetActionURL() templ.SafeURL {
	if c.ActionURL != "" {
		return templ.URL(c.ActionURL)
	}
	return "#"
}

func InputField(c Input) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if c.Type == Hidden {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input id=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.GetInputID()))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Name))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.GetInputType()))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" value=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Value))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"hidden\">")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><div class=\"flex items-center justify-between\"><label for=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.GetInputID()))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"block text-sm font-medium leading-6 text-zinc-900 dark:text-zinc-100\">")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(c.Label)
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/views/auth/components.templ`, Line: 60, Col: 120})
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> ")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			if c.ActionLabel != "" {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-sm\"><a href=\"")
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				var templ_7745c5c3_Var3 templ.SafeURL = c.GetActionURL()
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var3)))
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"font-semibold text-indigo-600 hover:text-indigo-500 dark:text-indigo-400 dark:hover:text-indigo-300\">")
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(c.ActionLabel)
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/views/auth/components.templ`, Line: 63, Col: 158})
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a></div>")
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"mt-2\"><input id=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.GetInputID()))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Name))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.GetInputType()))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" autocomplete=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Autocomplete))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			if c.Required {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" required")
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" value=\"")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Value))
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"block w-full rounded-md border-0 py-1.5 text-zinc-900 dark:text-zinc-100 shadow-sm dark:shadow-zinc-950 ring-1 ring-inset ring-zinc-300 dark:ring-zinc-600 placeholder:text-zinc-400 dark:placeholder:text-zinc-500 focus:ring-2 focus:ring-inset focus:ring-indigo-600 dark:focus:ring-indigo-300 sm:text-sm sm:leading-6 dark:bg-zinc-800\"></div>")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			if len(c.Errors) > 0 {
				for _, err := range c.Errors {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"mt-2 text-sm text-red-600 dark:text-red-500\" id=\"")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(c.Name + "-error"))
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(err)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/views/auth/components.templ`, Line: 72, Col: 90})
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return errtrace.Wrap(templ_7745c5c3_Err)
	})
}

func PrimaryButton(label string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var6 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var6 == nil {
			templ_7745c5c3_Var6 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><button type=\"submit\" id=\"submit-btn\" class=\"flex w-full justify-center rounded-md bg-indigo-600 dark:bg-indigo-500 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm dark:shadow-zinc-950 hover:bg-indigo-500 dark:hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:focus-visible:outline-indigo-500 cursor-pointer\"><span class=\"default-label\">")
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(label)
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/views/auth/components.templ`, Line: 82, Col: 38})
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span> <span class=\"loading-label hidden\">Sending...</span></button></div>")
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return errtrace.Wrap(templ_7745c5c3_Err)
	})
}

func Form(action string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"space-y-6\" hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(action))
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"innerHTML\" hx-indicator=\"#submit-btn\">")
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var8.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</form>")
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return errtrace.Wrap(templ_7745c5c3_Err)
	})
}
