// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package repository

import (
	"database/sql"
)

type User struct {
	ID        interface{}
	Email     string
	CreatedAt sql.NullTime
}
