// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string
	Email     string
	Password  sql.NullString
	CreatedAt time.Time
}

type UserSocialProfile struct {
	UserID     string
	SocialID   string
	SocialName string
	CreatedAt  sql.NullTime
}
