// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        string
	Name      string
	Title     sql.NullString
	LogoUrl   sql.NullString
	CreatedAt time.Time
}

type AccountMember struct {
	ID        string
	AccountID string
	UserID    string
	Name      sql.NullString
	Role      sql.NullString
	AvatarUrl sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID         string
	Email      string
	Password   sql.NullString
	CreatedAt  time.Time
	VerifiedAt sql.NullTime
}

type UserExternalProfile struct {
	UserID            string
	ProviderID        string
	ProviderType      string
	ExternalAccountID string
	CreatedAt         sql.NullTime
}
