// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_social_profiles.sql

package repository

import (
	"braces.dev/errtrace"
	"context"
)

const createUserSocialProfile = `-- name: CreateUserSocialProfile :exec
INSERT INTO user_external_profiles (user_id, provider_id, provider_type, external_account_id) VALUES (?, ?, ?, ?)
`

type CreateUserSocialProfileParams struct {
	UserID            string
	ProviderID        string
	ProviderType      string
	ExternalAccountID string
}

// CreateUserSocialProfile: Link a user to a social profile
func (q *Queries) CreateUserSocialProfile(ctx context.Context, arg CreateUserSocialProfileParams) error {
	_, err := q.db.ExecContext(ctx, createUserSocialProfile,
		arg.UserID,
		arg.ProviderID,
		arg.ProviderType,
		arg.ExternalAccountID,
	)
	return errtrace.Wrap(err)
}

const deleteUserSocialProfileBySocialID = `-- name: DeleteUserSocialProfileBySocialID :exec
DELETE FROM user_external_profiles
WHERE external_account_id = ?
AND provider_type = ?
AND provider_id = ?
`

type DeleteUserSocialProfileBySocialIDParams struct {
	ExternalAccountID string
	ProviderType      string
	ProviderID        string
}

// DeleteUserSocialProfileBySocialID: Delete a user's social profile by social id and social name
func (q *Queries) DeleteUserSocialProfileBySocialID(ctx context.Context, arg DeleteUserSocialProfileBySocialIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSocialProfileBySocialID, arg.ExternalAccountID, arg.ProviderType, arg.ProviderID)
	return errtrace.Wrap(err)
}

const deleteUserSocialProfilesByUserID = `-- name: DeleteUserSocialProfilesByUserID :exec
DELETE FROM user_external_profiles WHERE user_id = ?
`

// DeleteUserSocialProfilesByUserID: Delete a user's social profiles by user id
func (q *Queries) DeleteUserSocialProfilesByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSocialProfilesByUserID, userID)
	return errtrace.Wrap(err)
}

const getUserSocialProfileBySocialID = `-- name: GetUserSocialProfileBySocialID :one
SELECT user_id, provider_id, provider_type, external_account_id, created_at FROM user_external_profiles
WHERE external_account_id = ?
AND provider_type = ?
AND provider_id = ?
`

type GetUserSocialProfileBySocialIDParams struct {
	ExternalAccountID string
	ProviderType      string
	ProviderID        string
}

// GetUserSocialProfileBySocialID: Get a user's social profile by social id and social name
func (q *Queries) GetUserSocialProfileBySocialID(ctx context.Context, arg GetUserSocialProfileBySocialIDParams) (UserExternalProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserSocialProfileBySocialID, arg.ExternalAccountID, arg.ProviderType, arg.ProviderID)
	var i UserExternalProfile
	err := row.Scan(
		&i.UserID,
		&i.ProviderID,
		&i.ProviderType,
		&i.ExternalAccountID,
		&i.CreatedAt,
	)
	return i, errtrace.Wrap(err)
}

const getUserSocialProfileByUserID = `-- name: GetUserSocialProfileByUserID :one
SELECT user_id, provider_id, provider_type, external_account_id, created_at FROM user_external_profiles
WHERE user_id = ?
AND provider_type = ?
AND provider_id = ?
`

type GetUserSocialProfileByUserIDParams struct {
	UserID       string
	ProviderType string
	ProviderID   string
}

// GetUserSocialProfileByUserID: Get a user's social profile by user id and social name
func (q *Queries) GetUserSocialProfileByUserID(ctx context.Context, arg GetUserSocialProfileByUserIDParams) (UserExternalProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserSocialProfileByUserID, arg.UserID, arg.ProviderType, arg.ProviderID)
	var i UserExternalProfile
	err := row.Scan(
		&i.UserID,
		&i.ProviderID,
		&i.ProviderType,
		&i.ExternalAccountID,
		&i.CreatedAt,
	)
	return i, errtrace.Wrap(err)
}

const getUserSocialProfilesByUserID = `-- name: GetUserSocialProfilesByUserID :many
SELECT user_id, provider_id, provider_type, external_account_id, created_at FROM user_external_profiles WHERE user_id = ? ORDER BY created_at DESC
`

// GetUserSocialProfilesByUserID: Get a user's social profiles by user id
func (q *Queries) GetUserSocialProfilesByUserID(ctx context.Context, userID string) ([]UserExternalProfile, error) {
	rows, err := q.db.QueryContext(ctx, getUserSocialProfilesByUserID, userID)
	if err != nil {
		return nil, errtrace.Wrap(err)
	}
	defer rows.Close()
	var items []UserExternalProfile
	for rows.Next() {
		var i UserExternalProfile
		if err := rows.Scan(
			&i.UserID,
			&i.ProviderID,
			&i.ProviderType,
			&i.ExternalAccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, errtrace.Wrap(err)
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, errtrace.Wrap(err)
	}
	if err := rows.Err(); err != nil {
		return nil, errtrace.Wrap(err)
	}
	return items, nil
}
