root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/app"
pre_cmd = ["task view"]
cmd = "task build:air"
delay = 5000
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = [
	".*_templ.go",
	".*_test.go",
	".*_gen.go",
	"*.md",
	"*.log",
	"*.sql",
]
exclude_unchanged = true
follow_symlink = true
full_bin = ""
include_dir = ["web/templates/views", "web/src", "internal", "cmd/app"]
include_ext = ["templ", "css", "go"]
kill_delay = "2s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = true

[misc]
clean_on_exit = true
